# -*- coding: utf-8 -*-
"""Generate V1__baseline_jsh_erp.sql from docs/jsh_erp.sql (trim demo data)."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "docs" / "jsh_erp.sql"
DST = ROOT / "src" / "main" / "resources" / "db" / "migration" / "V1__baseline_jsh_erp.sql"

TABLES_NO_DATA = {
    "jsh_account", "jsh_account_head", "jsh_account_item", "jsh_depot", "jsh_depot_head",
    "jsh_depot_item", "jsh_in_out_item", "jsh_log", "jsh_material", "jsh_material_attribute",
    "jsh_material_category", "jsh_material_current_stock", "jsh_material_extend",
    "jsh_material_initial_stock", "jsh_material_property", "jsh_msg", "jsh_orga_user_rel",
    "jsh_organization", "jsh_person", "jsh_serial_number", "jsh_supplier",
    "jsh_system_config", "jsh_unit",
}

lines = SRC.read_text(encoding="utf-8").splitlines()
out = [
    "-- Flyway V1: ERP baseline (structure + essential system data, no demo business data)",
    "-- Generated by scripts/build_v1_baseline.py from docs/jsh_erp.sql",
    "",
]
current_table = ""
skip_insert = False
structure_re = re.compile(r"^-- Table structure for `(\w+)`")
records_re = re.compile(r"^-- Records of ")

for line in lines:
    m = structure_re.match(line)
    if m:
        current_table = m.group(1)
        skip_insert = False
    if records_re.match(line):
        skip_insert = current_table in TABLES_NO_DATA

    if skip_insert and line.startswith("INSERT INTO"):
        continue

    if current_table == "jsh_role" and line.startswith("INSERT INTO"):
        if "VALUES (4," not in line and "VALUES (10," not in line:
            continue

    if current_table == "jsh_user" and line.startswith("INSERT INTO"):
        if "'admin'" not in line:
            continue

    if current_table == "jsh_user_business" and line.startswith("INSERT INTO"):
        if "VALUES (5, 'RoleFunctions', '4'" not in line and "VALUES (38, 'UserRole', '120'" not in line:
            continue

    if current_table == "jsh_sequence" and line.startswith("INSERT INTO"):
        if "depot_number_seq" in line:
            out.append(
                "INSERT INTO `jsh_sequence` VALUES ('depot_number_seq', 1, 999999999999999999, 1, 1, '单据编号sequence');"
            )
        continue

    if current_table == "jsh_tenant" and line.startswith("INSERT INTO"):
        continue

    out.append(line)

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"Wrote {len(out)} lines to {DST}")
