-- Vehicle tables only (menus in V8)

CREATE TABLE IF NOT EXISTS `jsh_vehicle` (
  `id`                          BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
  `vehicle_purpose`             VARCHAR(20)   DEFAULT '乘用车' COMMENT '车辆用途：乘用车/商用车',
  `license_plate_province`      VARCHAR(10)   DEFAULT NULL COMMENT '车牌省份',
  `license_plate_no`            VARCHAR(20)   DEFAULT NULL COMMENT '车牌号',
  `no_plate`                    TINYINT(1)    DEFAULT 0 COMMENT '无牌：0否 1是',
  `vin`                         VARCHAR(20)   DEFAULT NULL COMMENT 'VIN码',
  `no_vin`                      TINYINT(1)    DEFAULT 0 COMMENT '暂无VIN：0否 1是',
  `vehicle_type`                VARCHAR(100)  DEFAULT NULL COMMENT '车型',
  `production_year`             VARCHAR(10)   DEFAULT NULL COMMENT '生产年份',
  `fuel_type`                   VARCHAR(30)   DEFAULT NULL COMMENT '燃料类型',
  `vehicle_category`            VARCHAR(50)   DEFAULT NULL COMMENT '车辆一级类型',
  `body_color`                  VARCHAR(30)   DEFAULT NULL COMMENT '车身颜色',
  `images`                      TEXT          DEFAULT NULL COMMENT '车辆图片（JSON数组，最多15张）',
  `vehicle_source`              VARCHAR(30)   DEFAULT '主动获取' COMMENT '车辆来源',
  `customer_name`               VARCHAR(60)   DEFAULT NULL COMMENT '客户姓名',
  `customer_phone`              VARCHAR(20)   DEFAULT NULL COMMENT '手机号码',
  `customer_level`              VARCHAR(30)   DEFAULT '默认客户' COMMENT '客户等级',
  `customer_gender`             VARCHAR(10)   DEFAULT '先生' COMMENT '性别',
  `customer_address`            VARCHAR(100)  DEFAULT NULL COMMENT '地址信息（省/市/区）',
  `customer_detail_address`     VARCHAR(255)  DEFAULT NULL COMMENT '详细地址',
  `vehicle_owner`               VARCHAR(60)   DEFAULT NULL COMMENT '车辆所有人',
  `brand_model`                 VARCHAR(100)  DEFAULT NULL COMMENT '品牌型号',
  `engine_no`                   VARCHAR(50)   DEFAULT NULL COMMENT '发动机号',
  `register_date`               DATE          DEFAULT NULL COMMENT '注册日期',
  `issue_date`                  DATE          DEFAULT NULL COMMENT '发证日期',
  `usage_nature`                VARCHAR(30)   DEFAULT NULL COMMENT '使用性质',
  `registration_images`         TEXT          DEFAULT NULL COMMENT '行驶证图片（JSON数组，最多2张）',
  `annual_check_date`           DATE          DEFAULT NULL COMMENT '年检日期',
  `traffic_insurance_expire`    DATE          DEFAULT NULL COMMENT '交强险到期',
  `commercial_insurance_expire` DATE          DEFAULT NULL COMMENT '商业险到期',
  `no_insurance`                TINYINT(1)    DEFAULT 0 COMMENT '未投保：0否 1是',
  `insurance_company`           VARCHAR(60)   DEFAULT NULL COMMENT '保险公司',
  `insurance_contact`           VARCHAR(60)   DEFAULT NULL COMMENT '保险联系人',
  `insurance_phone`             VARCHAR(20)   DEFAULT NULL COMMENT '保险联系电话',
  `repairer_name`               VARCHAR(60)   DEFAULT NULL COMMENT '送修人姓名',
  `repairer_contact`            VARCHAR(20)   DEFAULT NULL COMMENT '送修人联系方式',
  `repairer_gender`             VARCHAR(10)   DEFAULT '先生' COMMENT '送修人性别',
  `repairer_id_no`              VARCHAR(30)   DEFAULT NULL COMMENT '证件号码',
  `repairer_region`             VARCHAR(100)  DEFAULT NULL COMMENT '所在地区',
  `repairer_address`            VARCHAR(255)  DEFAULT NULL COMMENT '详细地址',
  `remark`                      VARCHAR(500)  DEFAULT NULL COMMENT '备注',
  `enabled`                     TINYINT(1)    DEFAULT 1 COMMENT '是否启用：0否 1是',
  `create_time`                 DATETIME      DEFAULT NULL COMMENT '创建时间',
  `update_time`                 DATETIME      DEFAULT NULL COMMENT '更新时间',
  `tenant_id`                   BIGINT        DEFAULT NULL COMMENT '租户ID',
  `delete_flag`                 VARCHAR(1)    DEFAULT '0' COMMENT '删除标志：0未删除 1已删除',
  PRIMARY KEY (`id`),
  INDEX `idx_tenant_id` (`tenant_id`),
  INDEX `idx_license_plate` (`license_plate_province`, `license_plate_no`),
  INDEX `idx_customer_phone` (`customer_phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户车辆信息表';

CREATE TABLE IF NOT EXISTS `jsh_vehicle_contact` (
  `id`            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `vehicle_id`    BIGINT       NOT NULL COMMENT '关联车辆ID',
  `contact_name`  VARCHAR(60)  DEFAULT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20)  DEFAULT NULL COMMENT '联系人手机号',
  `tenant_id`     BIGINT       DEFAULT NULL COMMENT '租户ID',
  `delete_flag`   VARCHAR(1)   DEFAULT '0' COMMENT '删除标志：0未删除 1已删除',
  `create_time`   DATETIME     DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `idx_vehicle_id` (`vehicle_id`),
  INDEX `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='车辆联系人表';
